---
- name: mdp-deployment-spn-dev
  project: mdp-demo
  organisation: JDPlayground
  subscriptions:
    - name: mdp-landing-zone
      id: 4cd088c7-964c-4e9f-bff2-81511318fe44
      resource_groups:
        - name: rg-mdp-data-dev-eun
          location: uksouth
          arm_roles:
            - owner
        - name: rg-mdp-syn-dev-eun
          location: uksouth
          arm_roles:
            - owner
        - name: rg-mdp-config-dev-eun
          location: uksouth
          arm_roles:
            - owner
  management_groups: []
  api_permissions:
    - name: azuregraph
      application_permissions:
        - Application.ReadWrite.OwnedBy
      delegated_permissions:
        - User.Read
    - name: msgraph
      application_permissions:
        - Group.Read.All
        - Group.Create
      delegated_permissions:
        - Application.Read.All