name: apply_github_settings
on: 
  workflow_dispatch:
    inputs:
      config_repo:
        default: live
        required: true
      dry_run_mode:
        default: false
        required: false
  schedule:
    - cron: '0 3 * * *'  # every day at 3am

jobs:
  apply_github_settings:
    runs-on: ubuntu-latest
    name: Applies standardised GitHub settings to target orgs/repos
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      
      - name: Run apply-github-settings.ps1
        run: |
          Install-Module powershell-yaml -Force -Scope CurrentUser -Repository PSGallery

          # process and validate the supplied config repo to use - default to 'test' if blank for some reason
          if ([string]::IsNullOrEmpty($env:CONFIG_REPO)) {
            $env:CONFIG_REPO = 'test'
          }
          $repoPath = "repos/$($env:CONFIG_REPO)"
          if (!(Test-Path $repoPath)) {
            Write-Error "Could not find config repo path: $repoPath"
            exit 1
          }
          
          # process dry_run_mode flag, if specified
          $dryRunMode = $null
          $dryRunMode = [bool]::TryParse($env:DRYRUN_MODE, [ref]$dryRunMode) ? $dryRunMode : $false

          ./codeops-scripts/apply-github-settings.ps1 -ConfigDirectory $repoPath -WhatIf:$dryRunMode
        shell: pwsh
        env:
          SSH_PRIVATE_KEY: ${{ secrets.DEPENDJINBOT_PRIVATE_KEY }}
          GITHUB_APP_ID: ${{ secrets.DEPENDJINBOT_APP_ID }}
          GITVERSION_NUGETVER: ${{ steps.run_gitversion.outputs.nuGetVersionV2 }}
          CONFIG_REPO: ${{ github.event.inputs.config_repo }}
          DATALAKE_NAME: ${{ secrets.DATALAKE_NAME }}
          DATALAKE_FILESYSTEM: ${{ secrets.DATALAKE_FILESYSTEM }}
          DATALAKE_DIRECTORY: ${{ secrets.DATALAKE_DIRECTORY }}
          DATALAKE_SASTOKEN: ${{ secrets.DATALAKE_SASTOKEN }}
          DRYRUN_MODE: ${{ github.event.inputs.dry_run_mode }}
          
